apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: j8xc068qf-python 
  janus-idp.io/tekton: j8xc068qf-python
  backstage.io/kubernetes-id: j8xc068qf-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j8xc068qf-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml